Update provisioner and Ops manager with coredge service related change
Signed-off-by: souravbiswassanto <saurov@appscode.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,13 +19,13 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - name: Set up Go 1.25
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
         with:
           go-version: '1.25'
         id: go
 
       - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
+        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
 
       - name: Prepare Host
         run: |
@@ -48,173 +48,15 @@ jobs:
         run: |
           echo "all db dashboards"
           helm template charts/kubedb-grafana-dashboards > /tmp/kubedb-grafana-dashboards-manifests.yaml
-          echo "-----------------------------------------"
-          echo "cassandra dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Cassandra=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "druid dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Druid=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "elasticsearch dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Elasticsearch=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "ferretdb dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.FerretDB=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "hazelcast dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Hazelcast=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "ignite dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Ignite=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "kafka dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Kafka=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "mariadb dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.MariaDB=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "memcached dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Memcached=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "mongodb dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.MongoDB=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "mssqlserver dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.MSSQLserver=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "mysql dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.MySQL=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "pgpool dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Pgpool=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "perconaxtradb dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.PerconaXtraDB=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "postgres dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Postgres=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "proxysql dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.ProxySQL=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "rabbitmq dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.RabbitMQ=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "redis dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Redis=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "singlestore dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.SingleStore=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "solr dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Solr=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
-
-          echo "-----------------------------------------"
-          echo "zookeeper dashboard with alerts"
-          helm template charts/kubedb-grafana-dashboards \
-          -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
-          --set featureGates.Zookeeper=true \
-          --set app.name=mydb \
-          --set app.namespace=demo
+          for db in Cassandra Druid Elasticsearch Hazelcast Ignite Kafka MariaDB Memcached MongoDB MSSQLserver MySQL Pgpool PerconaXtraDB Postgres ProxySQL RabbitMQ Redis SingleStore Solr Zookeeper; do
+            echo "-----------------------------------------"
+            echo "${db} dashboard with alerts"
+            helm template charts/kubedb-grafana-dashboards \
+              -f charts/kubedb-grafana-dashboards/ci/all-false-values.yaml \
+              --set featureGates.${db}=true \
+              --set app.name=mydb \
+              --set app.namespace=demo
+          done
 
   kubernetes:
     name: Kubernetes
@@ -224,7 +66,7 @@ jobs:
       matrix:
         k8s: [v1.29.14, v1.31.14, v1.33.7, v1.35.0]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
 
       - name: Install yq
         run: |
@@ -234,16 +76,13 @@ jobs:
 
       - name: Create Kubernetes ${{ matrix.k8s }} cluster
         id: kind
-        uses: engineerd/setup-kind@v0.5.0
+        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
         with:
           version: v0.31.0
-          image: kindest/node:${{ matrix.k8s }}
+          node_image: kindest/node:${{ matrix.k8s }}
 
       - name: Prepare cluster for testing
         id: local-path
-        env:
-          USERNAME: 1gtm
-          REGISTRY_SECRET: regcred
         run: |
           echo "waiting for nodes to be ready ..."
           kubectl wait --for=condition=Ready nodes --all --timeout=5m
@@ -258,8 +97,20 @@ jobs:
         run: |
           export KUBECONFIG="${HOME}/.kube/config"
           CLUSTER_UID=$(kubectl get ns kube-system -o=jsonpath='{.metadata.uid}')
-          LICENSE_KEY=$(curl -X POST -d "name=1gtm&email=1gtm@appscode.com&product=kubedb-enterprise&cluster=${CLUSTER_UID}&tos=true&token=${BYTEBUILDERS_LICENSE_TOKEN}" https://license-issuer.appscode.com/issue-license)
-          echo "${LICENSE_KEY}" > /tmp/license.txt
+          if ! curl --fail-with-body -sS -X POST \
+            --data-urlencode "name=1gtm" \
+            --data-urlencode "email=1gtm@appscode.com" \
+            --data-urlencode "product=kubedb-enterprise" \
+            --data-urlencode "cluster=${CLUSTER_UID}" \
+            --data-urlencode "tos=true" \
+            --data-urlencode "token=${BYTEBUILDERS_LICENSE_TOKEN}" \
+            -o /tmp/license.txt \
+            https://license-issuer.appscode.com/issue-license; then
+            echo "license issuer request failed; response body:"
+            cat /tmp/license.txt
+            exit 1
+          fi
+          LICENSE_KEY=$(cat /tmp/license.txt)
           # ref: https://github.com/mikefarah/yq/issues/230#issuecomment-487458629
           yqq w -i ./charts/kubedb-provisioner/ci/ci-values.yaml license --tag '!!str' -- "${LICENSE_KEY}"
           yqq w -i ./charts/kubedb-ops-manager/ci/ci-values.yaml license --tag '!!str' -- "${LICENSE_KEY}"
